# Generated by Django 6.0.3 on 2026-03-04 00:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Balance (INR)')),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('is_frozen', models.BooleanField(default=False, help_text='Frozen wallets cannot send or receive funds.')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='PlatformCommission',
            fields=[
                ('job', models.OneToOneField(db_column='job_id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='commission', serialize=False, to='marketplace.job')),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Commission %')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Commission Amount (INR)')),
                ('is_settled', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Commission',
                'verbose_name_plural': 'Platform Commissions',
                'db_table': 'platform_commissions',
                'constraints': [models.CheckConstraint(condition=models.Q(('commission_percentage__gte', 0), ('commission_percentage__lte', 100)), name='chk_commission_pct_range')],
            },
        ),
        migrations.CreateModel(
            name='PaymentDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raised_by_type', models.CharField(help_text="'customer' or 'worker'", max_length=20)),
                ('dispute_type', models.CharField(blank=True, max_length=50)),
                ('amount_disputed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('evidence_urls', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='marketplace.job')),
                ('raised_by', models.ForeignKey(db_column='raised_by', on_delete=django.db.models.deletion.PROTECT, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Dispute',
                'verbose_name_plural': 'Payment Disputes',
                'db_table': 'payment_disputes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_disputes_status'), models.Index(fields=['job'], name='idx_disputes_job')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(db_column='rating_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Star Rating')),
                ('review_text', models.TextField(blank=True)),
                ('rating_type', models.CharField(default='job_review', help_text="Type of review: 'job_review' or 'worker_review'", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(db_column='from_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='marketplace.job')),
                ('to_user', models.ForeignKey(db_column='to_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'ratings',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating_value__gte', 1), ('rating_value__lte', 5)), name='chk_rating_value_range')],
                'unique_together': {('job', 'from_user', 'rating_type')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(db_column='transaction_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('payout', 'Worker Payout'), ('top_up', 'Wallet Top-Up'), ('reversal', 'Reversal')], db_index=True, default='payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount (INR)')),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('transaction_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='upi, card, wallet, netbanking', max_length=30)),
                ('gateway_reference', models.CharField(blank=True, max_length=255, verbose_name='Payment Gateway Ref ID')),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(blank=True, db_column='from_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, db_column='job_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='marketplace.job')),
                ('to_user', models.ForeignKey(blank=True, db_column='to_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_status'], name='idx_txn_status'), models.Index(fields=['job'], name='idx_txn_job'), models.Index(fields=['from_user'], name='idx_txn_from'), models.Index(fields=['to_user'], name='idx_txn_to')],
            },
        ),
    ]
