# Generated by Django 6.0.3 on 2026-03-04 00:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(db_column='admin_action_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(db_index=True, max_length=50)),
                ('target_entity_type', models.CharField(blank=True, max_length=50)),
                ('target_entity_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(db_column='admin_user_id', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action',
                'verbose_name_plural': 'Admin Actions',
                'db_table': 'admin_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(db_index=True, help_text='create, update, delete, login, logout, ban', max_length=50)),
                ('target_type', models.CharField(blank=True, db_index=True, help_text='entity type: user, job, worker, system', max_length=50)),
                ('target_id', models.UUIDField(blank=True, help_text='ID of the affected entity', null=True)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, db_column='admin_id', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type'], name='idx_al_action'), models.Index(fields=['target_type'], name='idx_al_target'), models.Index(fields=['created_at'], name='idx_al_date')],
            },
        ),
        migrations.CreateModel(
            name='BannedEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.UUIDField(db_index=True, help_text='ID of the banned entity.', verbose_name='Entity UUID')),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('worker', 'Worker'), ('ip', 'IP Address'), ('device', 'Device')], db_index=True, max_length=20)),
                ('reason', models.TextField(verbose_name='Ban Reason')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Currently Banned')),
                ('expires_at', models.DateTimeField(blank=True, help_text='If null, ban is permanent.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banned_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banned Entity',
                'verbose_name_plural': 'Banned Entities',
                'db_table': 'banned_entities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_id', 'entity_type'], name='idx_ban_entity'), models.Index(fields=['is_active'], name='idx_ban_active')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_entity_type', models.CharField(blank=True, help_text="e.g. 'user', 'worker', 'job'", max_length=50)),
                ('target_entity_id', models.UUIDField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('abuse', 'Abuse / Harassment'), ('scam', 'Scam / Fraud'), ('bug', 'Bug / Technical Issue'), ('fake', 'Fake Profile'), ('spam', 'Spam'), ('other', 'Other')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(db_column='reporter_id', on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_reports_status'), models.Index(fields=['report_type'], name='idx_reports_type'), models.Index(fields=['reporter'], name='idx_reports_reporter')],
            },
        ),
    ]
