# Generated by Django 6.0.3 on 2026-03-04 00:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(db_column='address_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, help_text='e.g. Home, Office', max_length=50)),
                ('address_line', models.TextField(verbose_name='Full Address')),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=255, verbose_name='Icon Identifier')),
                ('base_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Base Rate (INR)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'is_deleted'], name='idx_cat_active'), models.Index(fields=['name'], name='idx_cat_name')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(db_column='job_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], db_index=True, default='pending', max_length=30, verbose_name='Job Status')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Final Price (INR)')),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, db_column='address_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='marketplace.address')),
                ('category', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='marketplace.category')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='assigned', max_length=30)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='marketplace.job')),
                ('worker', models.ForeignKey(db_column='worker_id', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='accounts.workerprofile')),
            ],
            options={
                'verbose_name': 'Job Assignment',
                'verbose_name_plural': 'Job Assignments',
                'db_table': 'job_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], max_length=30)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='marketplace.job')),
            ],
            options={
                'verbose_name': 'Job Status History',
                'verbose_name_plural': 'Job Status Histories',
                'db_table': 'job_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('rate_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custom Rate Override (INR)')),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='worker_categories', to='marketplace.category')),
                ('worker', models.ForeignKey(db_column='worker_id', on_delete=django.db.models.deletion.CASCADE, related_name='worker_categories', to='accounts.workerprofile')),
            ],
            options={
                'verbose_name': 'Worker Category',
                'verbose_name_plural': 'Worker Categories',
                'db_table': 'worker_categories',
            },
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'is_default'], name='idx_addr_user_default'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='idx_addr_city'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_status', 'scheduled_at'], name='idx_jobs_status_date'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', 'job_status'], name='idx_jobs_user_status'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_deleted'], name='idx_jobs_deleted'),
        ),
        migrations.AddIndex(
            model_name='jobassignment',
            index=models.Index(fields=['job', 'assignment_status'], name='idx_ja_job_status'),
        ),
        migrations.AddIndex(
            model_name='jobassignment',
            index=models.Index(fields=['worker', 'assignment_status'], name='idx_ja_worker_status'),
        ),
        migrations.AddIndex(
            model_name='jobstatushistory',
            index=models.Index(fields=['job'], name='idx_jsh_job'),
        ),
        migrations.AddIndex(
            model_name='workercategory',
            index=models.Index(fields=['worker', 'category'], name='idx_wc_composite'),
        ),
        migrations.AddConstraint(
            model_name='workercategory',
            constraint=models.UniqueConstraint(fields=('worker', 'category'), name='uniq_worker_category'),
        ),
    ]
