# Generated by Django 6.0.3 on 2026-03-04 00:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Statistics Date')),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('completed_bookings', models.PositiveIntegerField(default=0)),
                ('cancelled_bookings', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_payouts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('platform_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('new_workers', models.PositiveIntegerField(default=0)),
                ('active_workers', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Statistic',
                'verbose_name_plural': 'Daily Statistics',
                'db_table': 'daily_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.TextField(help_text="Unique configuration identifier (e.g. 'maintenance_mode').", primary_key=True, serialize=False, verbose_name='Setting Key')),
                ('value', models.JSONField(verbose_name='Setting Value')),
                ('description', models.TextField(blank=True, verbose_name='Usage Description')),
                ('category', models.CharField(blank=True, db_index=True, help_text='Grouping label for admin UI.', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='If True, this setting is readable by the frontend.', verbose_name='Exposed to Public API')),
                ('is_editable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Arbitrary contextual data payload.')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='If null, this is a broadcast notification to all staff.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'db_table': 'admin_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', 'recipient'], name='idx_notif_unread'), models.Index(fields=['priority'], name='idx_notif_priority')],
            },
        ),
    ]
